version: '3.3'

services:
  basket.api:
    image: hms/basket.api
    depends_on:
      - basket.data
      - identity.api
      - rabbitmq

  catalog.api:
    image: hms/catalog.api
    depends_on:
      - sql.data
      - rabbitmq

  identity.api:
    image: hms/identity.api
    depends_on:
      - sql.data

  ordering.api:
    image: hms/ordering.api
    depends_on:
      - sql.data
      - rabbitmq

  marketing.api:
    image: hms/marketing.api   
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq      

  webspa:
    image: hms/webspa
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api
      - marketing.api

  webmvc:
    image: hms/webmvc  
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api
      - marketing.api

  webstatus:
    image: hms/webstatus
    
  payment.api:
    image: hms/payment.api
    depends_on:
      - rabbitmq         

  locations.api:
    image: hms/locations.api
    depends_on:
      - nosql.data
      - rabbitmq

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
  
  nosql.data:
    image: mongo
  
  basket.data:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

