version: '2'

services:
  hmsweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Database=CatalogDb;User Id=sa;Password=Pass@word
      - CatalogBaseUrl=http://localhost:5106
    ports:
      - "5106:5106"

  sql.data:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
