version: '2'

services:
  hmsweb:
    image: hms/web
    build:
      context: ./hmsWeb
      dockerfile: Dockerfile
    depends_on:
      - sql.data
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
